# Generated by Django 4.2.1 on 2023-06-01 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='phone',
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='education',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='first_name',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='job_experience',
            field=models.TextField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='last_name',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='phone_number',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='skills',
            field=models.TextField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='address',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='email',
            field=models.EmailField(default='N/A', max_length=100),
        ),
    ]
